services:
  artemis:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: superman
    volumes:
      - artemis_data:/var/lib/artemis/data

volumes:
  artemis_data:
