server:
  port: 8120
  servlet:
    context-path: /jms-async

management:
  endpoint:
    health:
      show-details: 'always'
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  artemis:
    mode: native
    #    broker-url: tcp://localhost:61616?jms.useAsyncSend=true
    user: admin
    password: superman
  cloud:
    discovery:
      client:
        simple:
          instances:
            greetings:
              - uri: http://localhost:8130
            more-greetings:
              - uri: http://localhost:8131

debug: true